// galleryComponents.js

let galleryComponents = [
    {
        name: 'LED Green',
        texture: "src/media/texture/prop/electronics/led/led_green.svg",
        theId: "desk_001",
        category: "electronics",
        sizeX: 200,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Resistor 100 Ohm',
        texture: "src/media/texture/prop/electronics/resistor/resistor_100_ohm.svg",
        theId: "resistor_100_ohm",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Two AA Batteries',
        texture: "src/media/texture/prop/electronics/batteries/two_aa_batteries.svg",
        theId: "two_aa_batteries",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Capacitor Electrolytic',
        texture: "src/media/texture/prop/electronics/capacitors/electrolytic/capacitor_electrolytic.svg",
        theId: "capacitor_electrolytic",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Transistor - BJT - NPN 3904',
        texture: "src/media/texture/prop/electronics/transistors/bjt/transistor_bjt_npn_3904.svg",
        theId: "transistor_bjt_npn_3904",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'LDR Light Dependent Resistor',
        texture: "src/media/texture/prop/electronics/ldr/ldr_light_dependent_resistor.svg",
        theId: "ldr_light_dependent_resistor",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Wire - Lead - Positive - Red',
        texture: "src/media/texture/prop/electronics/wire/lead/wire_positive_red.svg",
        theId: "wire_positive_red",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Wire - Lead - Negative - Green',
        texture: "src/media/texture/prop/electronics/wire/lead/wire_negative_green.svg",
        theId: "wire_positive_red",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Cardboard Box',
        texture: "src/media/texture/prop/electronics/cardboard_box/cardboard_box.png",
        theId: "cardboard_box",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Rails - Paperclips - 10',
        texture: "src/media/texture/prop/electronics/rails/rails_paperclips_10.svg",
        theId: "rails_paperclips_10",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'IR Infrared Receiver',
        texture: "src/media/texture/prop/electronics/ir/ir_receiver/ir_receiver.svg",
        theId: "ir_receiver",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Wire Positive Curved',
        texture: "src/media/texture/prop/electronics/wire/battery/wire_positive_red_curved.svg",
        theId: "wire_positive_red_curved",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

    {
        name: 'Wire Negative Curved',
        texture: "src/media/texture/prop/electronics/wire/battery/wire_negative_green_curved.svg",
        theId: "wire_positive_green_curved",
        category: "electronics",
        sizeX: 100,
        posX: 0,
        posY: 20,
        type: "webp",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "propStyle",
        rotationAmount: 0 + "deg",
        theBrightness: 1.0,
        theContrast: 1.3,
        theHue: 0,
        theSaturation: 0.5,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
    },

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

