// galleryYachts.js

let galleryYachts =
[
{
    name: "yacht_001",
    texture: "src/media/texture/prop/yacht/yacht_001.webp",
    theId: "yacht_001",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_002",
    texture: "src/media/texture/prop/yacht/yacht_002.webp",
    theId: "yacht_002",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_003",
    texture: "src/media/texture/prop/yacht/yacht_003.webp",
    theId: "yacht_003",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_004",
    texture: "src/media/texture/prop/yacht/yacht_004.webp",
    theId: "yacht_004",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_005",
    texture: "src/media/texture/prop/yacht/yacht_005.webp",
    theId: "yacht_005",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_006",
    texture: "src/media/texture/prop/yacht/yacht_006.webp",
    theId: "yacht_006",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_007",
    texture: "src/media/texture/prop/yacht/yacht_007.webp",
    theId: "yacht_007",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "yacht_008",
    texture: "src/media/texture/prop/yacht/yacht_008.webp",
    theId: "yacht_008",
    category: "yacht",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

