// galleryJeeps.js

let galleryJeeps =
[
{
    name: "jeep_001",
    texture: "src/media/texture/prop/jeeps/jeep_001.webp",
    theId: "jeep_001",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jeep_002",
    texture: "src/media/texture/prop/jeeps/jeep_002.webp",
    theId: "jeep_002",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jeep_003",
    texture: "src/media/texture/prop/jeeps/jeep_003.webp",
    theId: "jeep_003",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jeep_004",
    texture: "src/media/texture/prop/jeeps/jeep_004.webp",
    theId: "jeep_004",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jeep_005",
    texture: "src/media/texture/prop/jeeps/jeep_005.webp",
    theId: "jeep_005",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jeep_006",
    texture: "src/media/texture/prop/jeeps/jeep_006.webp",
    theId: "jeep_006",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jeep_007",
    texture: "src/media/texture/prop/jeeps/jeep_007.webp",
    theId: "jeep_007",
    category: "jeep",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

