// galleryProps.js

let galleryProps = [
{
    name: "cardboard_box",
    texture: "src/media/texture/prop/cardboard_box/cardboard_box.webp",
    theId: "cardboard_box",
    category: "props",
    sizeX: 150,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "lantern",
    texture: "src/media/texture/prop/lantern/lantern.webp",
    theId: "lantern",
    category: "props",
    sizeX: 150,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "flashlight_001",
    texture: "src/media/texture/prop/flashlight/flashlight.webp",
    theId: "flashlight_001",
    category: "props",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "table_round_001",
    texture: "src/media/texture/prop/table/round/prop_table_001.webp",
    theId: "table_round_001",
    category: "props",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "table_round_002",
    texture: "src/media/texture/prop/table/round/round_table_002.png",
    theId: "table_round_002",
    category: "props",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "table_round_003",
    texture: "src/media/texture/prop/table/round/round_table_003.png",
    theId: "table_round_003",
    category: "props",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "rectangle_table_001",
    texture: "src/media/texture/prop/table/rectangle/rectangle_table_001.png",
    theId: "rectangle_table_001",
    category: "props",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

