// galleryJets.js

let galleryJets =
[
{
    name: "f16_fighting_falcon",
    texture: "src/media/texture/prop/jet/f16_fighting_falcon/f16_fighting_falcon.webp",
    theId: "f16_fighting_falcon",
    category: "jet",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    // https://en.wikipedia.org/wiki/General_Dynamics_F-16_Fighting_Falcon
},

{
    name: "f-35a_lightning_II_joint_strike_fighter",
    texture: "src/media/texture/prop/jet/f-35a_lightning_II_joint_strike_fighter/f-35a_lightning_II_joint_strike_fighter.webp",
    theId: "f-35a_lightning_II_joint_strike_fighter",
    category: "jet",
    country: "America",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "china_j-20",
    texture: "src/media/texture/prop/jet/china_j-20/china_j-20.webp",
    theId: "china_j-20",
    category: "jet",
    country: "China",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    // https://en.wikipedia.org/wiki/Chengdu_J-20
},

{
    name: "jet_001",
    texture: "src/media/texture/prop/jet/jet_001.webp",
    theId: "jet_001",
    category: "jet",
    country: "Unknown",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jet_002",
    texture: "src/media/texture/prop/jet/jet_002.webp",
    theId: "jet_002",
    category: "jet",
    country: "Unknown",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jet_003",
    texture: "src/media/texture/prop/jet/jet_003.webp",
    theId: "jet_003",
    category: "jet",
    country: "Unknown",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jet_004",
    texture: "src/media/texture/prop/jet/jet_004.webp",
    theId: "jet_004",
    category: "jet",
    country: "Unknown",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jet_005",
    texture: "src/media/texture/prop/jet/jet_005.webp",
    theId: "jet_005",
    category: "jet",
    country: "Unknown",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "jet_006",
    texture: "src/media/texture/prop/jet/jet_006.webp",
    theId: "jet_006",
    category: "jet",
    country: "Unknown",
    sizeX: 256,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

