// galleryHumvees.js

let galleryHumvees =
[
{
    name: "humvee_001",
    texture: "src/media/texture/prop/humvee/humvee_001.webp",
    theId: "humvee_001",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_002",
    texture: "src/media/texture/prop/humvee/humvee_002.webp",
    theId: "humvee_002",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_003",
    texture: "src/media/texture/prop/humvee/humvee_003.webp",
    theId: "humvee_003",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_004",
    texture: "src/media/texture/prop/humvee/humvee_004.webp",
    theId: "humvee_004",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_005",
    texture: "src/media/texture/prop/humvee/humvee_005.webp",
    theId: "humvee_005",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_006",
    texture: "src/media/texture/prop/humvee/humvee_006.webp",
    theId: "humvee_006",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_007",
    texture: "src/media/texture/prop/humvee/humvee_007.webp",
    theId: "humvee_007",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "humvee_008",
    texture: "src/media/texture/prop/humvee/humvee_008.webp",
    theId: "humvee_008",
    category: "humvee",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

