// galleryDesks.js

let galleryDesks = [
{
    name: "desk_001",
    texture: "src/media/texture/prop/desk/desk_001.webp",
    theId: "desk_001",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "desk_002",
    texture: "src/media/texture/prop/desk/desk_002.webp",
    theId: "desk_002",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "desk_003",
    texture: "src/media/texture/prop/desk/desk_003.webp",
    theId: "desk_003",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "desk_004",
    texture: "src/media/texture/prop/desk/desk_004.webp",
    theId: "desk_004",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "desk_005",
    texture: "src/media/texture/prop/desk/desk_005.webp",
    theId: "desk_005",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "desk_006",
    texture: "src/media/texture/prop/desk/desk_006.webp",
    theId: "desk_006",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "desk_008",
    texture: "src/media/texture/prop/desk/desk_008.webp",
    theId: "desk_008",
    category: "desk",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},
];