// galleryMilitaryMales.js

let galleryMilitaryMales = 
[
    {
        name: "usarmy001",
        texture: "src/media/texture/model/military/male/001.webp",
        theId: "usmilitary_001",
        sizeX: '200',
        posX: "20", 
        posY: "20",
        rotationAmount: 0 + "deg",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "characterStyle",
        theContrast: 1.0,
        theBrightness: 1.0,
        theHue: 0,
        theSaturation: 1.0,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
        type: "webp",
        category: "military_males",
        realName: "",
    },

    {
        name: "usarmy002",
        texture: "src/media/texture/model/military/male/002.webp",
        theId: "usmilitary_002",
        sizeX: '200',
        posX: "20", 
        posY: "20",
        rotationAmount: 0 + "deg",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "characterStyle",
        theContrast: 1.0,
        theBrightness: 1.0,
        theHue: 0,
        theSaturation: 1.0,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
        type: "webp",
        category: "military_males",
        realName: "",
    },

    {
        name: "usarmy003",
        texture: "src/media/texture/model/military/male/003.webp",
        theId: "usmilitary_003",
        sizeX: '200',
        posX: "20", 
        posY: "20",
        rotationAmount: 0 + "deg",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "characterStyle",
        theContrast: 1.0,
        theBrightness: 1.0,
        theHue: 0,
        theSaturation: 1.0,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
        type: "webp",
        category: "military_males",
        realName: "",
    },

    {
        name: "usarmy004",
        texture: "src/media/texture/model/military/male/004.webp",
        theId: "usmilitary_004",
        sizeX: '200',
        posX: "20", 
        posY: "20",
        rotationAmount: 0 + "deg",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "characterStyle",
        theContrast: 1.0,
        theBrightness: 1.0,
        theHue: 0,
        theSaturation: 1.0,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
        type: "webp",
        category: "military_males",
        realName: "",
    },

    {
        name: "usarmy005",
        texture: "src/media/texture/model/military/male/005.webp",
        theId: "usmilitary_005",
        sizeX: '200',
        posX: "20", 
        posY: "20",
        rotationAmount: 0 + "deg",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "characterStyle",
        theContrast: 1.0,
        theBrightness: 1.0,
        theHue: 0,
        theSaturation: 1.0,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
        type: "webp",
        category: "military_males",
        realName: "",
    },

    {
        name: "usarmy006",
        texture: "src/media/texture/model/military/male/006.webp",
        theId: "usmilitary_006",
        sizeX: '200',
        posX: "20", 
        posY: "20",
        rotationAmount: 0 + "deg",
        theLayer: 5,
        flipHorizontal: false,
        flipVertical: false,
        className: "characterStyle",
        theContrast: 1.0,
        theBrightness: 1.0,
        theHue: 0,
        theSaturation: 1.0,
        theBlur: 0,
        theInvert: 0,
        theGrayscale: 0,
        theSepia: 0,
        theDropShadowX: "10px",
        theDropShadowY: "10px",
        theDropShadowBlurRadius: "10px",
        theDropShadowColor: "black",
        type: "webp",
        category: "military_males",
        realName: "",
    },
];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

