// galleryPeople.js

let galleryPeople = [
{
    name: "Bruce",
    texture: "src/media/texture/model/people/Bruce.webp",
    theId: "Bruce",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "Craig",
    texture: "src/media/texture/model/people/Craig.webp",
    theId: "Craig",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "Darren",
    texture: "src/media/texture/model/people/Darren.webp",
    theId: "Darren",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "Dave",
    texture: "src/media/texture/model/people/Dave.webp",
    theId: "Dave",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "Debra",
    texture: "src/media/texture/model/people/Debra.webp",
    theId: "Debra",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "Eric",
    texture: "src/media/texture/model/people/Eric.webp",
    theId: "Eric",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "Fred",
    texture: "src/media/texture/model/people/Fred.webp",
    theId: "Fred",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "James",
    texture: "src/media/texture/model/people/James.webp",
    theId: "James",
    category: "person",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 0.5,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];