// galleryDronesMilitary.js

let galleryDronesMilitary = [
{
    name: "mq-1c_warrior",
    texture: "src/media/texture/prop/drones/military/mq-1c_warrior/mq-1c_warrior.webp",
    theId: "mq-1c_warrior",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "mq-1c_warrior",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
    // https://en.wikipedia.org/wiki/File:MQ-1C_Warrior_(2005-08-11).jpg
},

{
    name: "drone_001",
    texture: "src/media/texture/prop/drones/military/drone_001.webp",
    theId: "drone_001",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_001",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_002",
    texture: "src/media/texture/prop/drones/military/drone_002.webp",
    theId: "drone_002",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_002",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_003",
    texture: "src/media/texture/prop/drones/military/drone_003.webp",
    theId: "drone_003",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_003",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_004",
    texture: "src/media/texture/prop/drones/military/drone_004.webp",
    theId: "drone_004",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_004",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_005",
    texture: "src/media/texture/prop/drones/military/drone_005.webp",
    theId: "drone_005",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_005",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_006",
    texture: "src/media/texture/prop/drones/military/drone_006.webp",
    theId: "drone_006",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_006",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_007",
    texture: "src/media/texture/prop/drones/military/drone_007.webp",
    theId: "drone_007",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_007",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

{
    name: "drone_008",
    texture: "src/media/texture/prop/drones/military/drone_008.webp",
    theId: "drone_008",
    sizeX: "200",
    posX: "0", 
    posY: "20",
    theOpacity: 1,
    type: "webp",
    category: "drone_military",
    realName: "drone_008",
    theLayer: 5,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.3,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    info: "Information",
    rotationAmount: 0 + 'deg'
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2026
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

