// galleryTanks.js

let galleryTanks = [
{
    name: "M1_Abrams_Tank",
    texture: "src/media/texture/prop/tank/m1_abrams/m1_abrams.webp",
    theId: "M1_Abrams_Tank",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    // https://en.wikipedia.org/wiki/M1_Abrams
},

{
    name: "russian_army_t-14_armata",
    texture: "src/media/texture/prop/tank/russian_army_t-14_armata/russian_army_t-14_armata.webp",
    theId: "russian_army_t-14_armata",
    category: "tank",
    country: "Russia",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    // https://en.wikipedia.org/wiki/T-14_Armata
},

{
    name: "china_type-99-mbt",
    texture: "src/media/texture/prop/tank/china_type-99-mbt/china_type-99-mbt.png",
    theId: "china_type-99-mbt",
    category: "tank",
    country: "China",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "drone_tank_001",
    texture: "src/media/texture/prop/tank/drone_tanks/drone_tank_001.webp",
    theId: "drone_tank_001",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_001",
    texture: "src/media/texture/prop/tank/tank_001.webp",
    theId: "tank_001",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_002",
    texture: "src/media/texture/prop/tank/tank_002.webp",
    theId: "tank_002",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_003",
    texture: "src/media/texture/prop/tank/tank_003.webp",
    theId: "tank_003",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_004",
    texture: "src/media/texture/prop/tank/tank_004.webp",
    theId: "tank_004",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_005",
    texture: "src/media/texture/prop/tank/tank_005.webp",
    theId: "tank_005",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_006",
    texture: "src/media/texture/prop/tank/tank_006.webp",
    theId: "tank_006",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    name: "tank_007",
    texture: "src/media/texture/prop/tank/tank_007.webp",
    theId: "tank_007",
    category: "tank",
    country: "America",
    sizeX: 200,
    posX: 0,
    posY: 20,
    type: "webp",
    theLayer: 5,
    theOpacity: 1,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    rotationAmount: 0 + "deg",
    theBrightness: 1.0,
    theContrast: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

