// scene_led_circuit_001.js

let scene_led_circuit_001 = [
{
    // scene info
    scene: "scene_led_circuit_001",
    sceneTitle: "Light Circuit 001",
    description: "Light Circuit 001 is a simple LED Circuit",
    //theIdToMove: "ayan1",

    daySetting: 1.0,
    nightSetting: 0.3,

    // background texture
    type: "webp",
    category: "background",
    className: "theBackground2",
    name: "The background",
    texture: "src/media/texture/background/electronics/electronics_lab_001.jpg",
    theId: "theBgId",
    sizeX: 800,
    //theX: 0,
    //theY: 105,
    // cover: "cover" // cover  // contain
},

// character - ayan1
{
    type: "webp",
    category: "character",
    name: "ayan1",
    texture: "src/media/texture/model/ayan/standing/model_ayan_standing_right.webp",
    theId: "ayan1",
    sizeX: 50,
    theX: 373,
    theY: 245,
    flipHorizontal: false,
    flipVertical: false,
    className: "characterStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "circuit_board",
    texture: "src/media/texture/prop/electronics/cardboard_box/cardboard_box.png",
    theId: "ayan1",
    sizeX: 400,
    theX: 175,
    theY: 10,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "circuit_board",
    texture: "src/media/texture/prop/electronics/rails/rails_paperclips_10.svg",
    theId: "rails",
    sizeX: 185,
    theX: 280,
    theY: 75,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "led_green",
    texture: "src/media/texture/prop/electronics/led/led_green.svg",
    theId: "led_green",
    sizeX: 21,
    theX: 300,
    theY: 95,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "led_green",
    texture: "src/media/texture/prop/electronics/resistor/resistor_100_ohm.svg",
    theId: "resistor_100_ohm",
    sizeX: 21,
    theX: 317,
    theY: 145,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "batteries",
    texture: "src/media/texture/prop/electronics/batteries/two_aa_batteries.svg",
    theId: "two_aa_batteries",
    sizeX: 21,
    theX: 240,
    theY: 125,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "wire-positive",
    texture: "src/media/texture/prop/electronics/wire/lead/wire_positive_red.svg",
    theId: "wire_positive_red",
    sizeX: 6,
    theX: 299,
    theY: 74,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "wire-negative",
    texture: "src/media/texture/prop/electronics/wire/lead/wire_negative_green.svg",
    theId: "wire_negative_green",
    sizeX: 6,
    theX: 333,
    theY: 253,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "wire-positive-curved",
    texture: "src/media/texture/prop/electronics/wire/battery/wire_positive_red_curved.svg",
    theId: "wire_positive_red_curved",
    sizeX: 50,
    theX: 246,
    theY: 73,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

{
    type: "png",
    category: "prop",
    name: "wire-negative-curved",
    texture: "src/media/texture/prop/electronics/wire/battery/wire_negative_green_curved.svg",
    theId: "wire_negative_green_curved",
    sizeX: 50,
    theX: 247,
    theY: 211,
    flipHorizontal: false,
    flipVertical: false,
    className: "propStyle",
    theLayer: 4,
    // rotationAmount: 90 + "deg",
    theBrightness: 1.2,
    theContrast: 1.5,
},

];