// scene_desert_001.js

let scene_desert_001 = [
{
    // scene info
    scene: "scene_desert_001",
    sceneTitle: "desert",
    description: "The Desert",

    daySetting: 1.0,
    nightSetting: 0.4
},

{
    // theIdToMove: "ayan1",

    // background texture
    type: "webp",
    category: "background",
    className: "",
    name: "The background",
    texture: "src/media/texture/background/desert/001.webp",
    theId: "theBgId",
    theLayer: 1,
    sizeX: 1000,
    theX: 0,
    theY: -100,
    rotationAmount: 0 + "deg",
    theContrast: 1.0,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
    tileLevel: false,
    daySetting: 1.0,
    nightSetting: 0.3
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "china_j-20",
    texture: "src/media/texture/prop/jet/china_j-20/china_j-20.webp",
    theId: "china_j-20",
    theLayer: 1,
    sizeX: 256,
    theX: 290,
    theY: 125,
    rotationAmount: 0 + "deg",
    theContrast: 1.0,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "1.1px",
    theDropShadowY: "6.7px",
    theDropShadowBlurRadius: "4.1px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "f-35a_lightning_II_joint_strike_fighter.",
    texture: "src/media/texture/prop/jet/f-35a_lightning_II_joint_strike_fighter/f-35a_lightning_II_joint_strike_fighter.webp",
    theId: "f-35a_lightning_II_joint_strike_fighter.",
    theLayer: 1,
    sizeX: 256,
    theX: 1008,
    theY: 92,
    rotationAmount: 0 + "deg",
    theContrast: 1.0,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "2px",
    theDropShadowY: "5px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "f16_fighting_falcon",
    texture: "src/media/texture/prop/jet/f16_fighting_falcon/f16_fighting_falcon.webp",
    theId: "f16_fighting_falcon",
    theLayer: 1,
    sizeX: 256,
    theX: 533,
    theY: 55,
    rotationAmount: 28 + "deg",
    theContrast: 1.0,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "2.9px",
    theDropShadowY: "1.4px",
    theDropShadowBlurRadius: "2.6px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "russian_army_t-14_armata",
    texture: "src/media/texture/prop/tank/russian_army_t-14_armata/russian_army_t-14_armata.webp",
    theId: "russian_army_t-14_armata",
    theLayer: 1,
    sizeX: 256,
    theX: 365,
    theY: 442,
    rotationAmount: 0 + "deg",
    theContrast: 1.3,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "china_type-99-mbt",
    texture: "src/media/texture/prop/tank/china_type-99-mbt/china_type-99-mbt.png",
    theId: "china_type-99-mbt",
    theLayer: 1,
    sizeX: 200,
    theX: 615,
    theY: 401,
    rotationAmount: 0 + "deg",
    theContrast: 1.3,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "1.1px",
    theDropShadowY: "6.7px",
    theDropShadowBlurRadius: "3.1px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "m1_abrams",
    texture: "src/media/texture/prop/tank/m1_abrams/m1_abrams.webp",
    theId: "m1_abrams",
    theLayer: 1,
    sizeX: 76,
    theX: 115,
    theY: 169,
    rotationAmount: 0 + "deg",
    theContrast: 1.3,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "howitzer_m119_105mm",
    texture: "src/media/texture/prop/artillery/howitzer/howitzer_m119_105mm/howitzer_m119_105mm.webp",
    theId: "howitzer_m119_105mm",
    theLayer: 1,
    sizeX: 300,
    theX: 941,
    theY: 382,
    rotationAmount: 0 + "deg",
    theContrast: 1.3,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "m224_60mm",
    texture: "src/media/texture/prop/artillery/motar/m224_60mm/m224_60mm.webp",
    theId: "m224_60mm",
    theLayer: 1,
    sizeX: 300,
    theX: 692,
    theY: 480,
    rotationAmount: 0 + "deg",
    theContrast: 1.3,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "10px",
    theDropShadowY: "10px",
    theDropShadowBlurRadius: "10px",
    theDropShadowColor: "black",
},

{
    type: "webp",
    category: "prop",
    className: "propStyle",
    name: "mq-1c_warrior",
    texture: "src/media/texture/prop/drones/military/mq-1c_warrior/mq-1c_warrior.webp",
    theId: "mq-1c_warrior",
    theLayer: 1,
    sizeX: 76,
    theX: 270,
    theY: 8,
    rotationAmount: 0 + "deg",
    theContrast: 1.3,
    theBrightness: 1.0,
    theHue: 0,
    theSaturation: 1.0,
    theBlur: 0,
    theInvert: 0,
    theGrayscale: 0,
    theSepia: 0,
    theDropShadowX: "0px",
    theDropShadowY: "0px",
    theDropShadowBlurRadius: "2.6px",
    theDropShadowColor: "black",
},
];

//----//

// Dedicated to God the Father
// All Rights Reserved Christopher Andrew Topalian Copyright 2000-2025
// https://github.com/ChristopherTopalian
// https://github.com/ChristopherAndrewTopalian
// https://sites.google.com/view/CollegeOfScripting

